### PR TITLE
Document lobid-gnd search and navigation UI

### PR DESCRIPTION
**Pull request by fsteeg**
See https://github.com/hbz/lobid-gnd/issues/133

Suggestion for annoucement at http://twitter.com/lobidorg after merge:

> Nach einem ersten kleinen Usability-Test haben wir einen Überblick zu Suche und Navigation in der lobid-gnd Oberfläche geschrieben http://blog.lobid.org/2018/07/04/lobid-gnd-suche.html

### CODE REVIEW

**Comment by acka47** [comment]
Wir sollten ein anderes Beispiel für das präzise Eingrenzen der Treffermenge über Filter/Facetten nehmen. Vielleicht statt Ländercode "Deutschland" "Nordrhein-Westfalen" nehmen?http://test.lobid.org/gnd/search?filter=%2B%28type%3ANaturalGeographicUnit%29+%2B%28gndSubjectCategory.id%3A%22http%3A%2F%2Fd-nb.info%2Fstandards%2Fvocab%2Fgnd%2Fgnd-sc%2319.3%22%29+%2B%28geographicAreaCode.id%3A%22http%3A%2F%2Fd-nb.info%2Fstandards%2Fvocab%2Fgnd%2Fgeographic-area-code%23XA-DE-NW%22%29&size=100&format=html

**Comment by fsteeg** [comment]
@acka47 Pushed the updated sample, and the nav bar is updated in production ("Erkunden").

**Comment by acka47** [comment]
As discussed offline we might also say something about the result list in general, e.g. 10 results by default and buttons for larger lists plus paging options.

**Comment by fsteeg** [comment]
@acka47 Pushed additional updates.

**Comment by acka47** [comment]
+1 Merging

**Pull request merged**
