### PR TITLE
Add tagging support

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve https://github.com/lobid/lobid.github.com/issues/9

Based on http://longqian.me/2017/02/09/github-jekyll-tag/

Requires manual maintenance of tags. I've set up 3 tags for the lobid services, plus one additional technology tag for things not strictly related to the lobid services. I think this should work fine for us.

### CODE REVIEW

**Comment by acka47** [comment]
Looks good in principle. Is it possible to assign multiple tags? Also, we should probably say on the home page that these are tags.

**Comment by acka47** [comment]
`vocabulary-choices.html` should definitely be tagged `lobid-resources`. Also, I am not sure that the `technology` tag is the best umbrella term for non-service-specific posts. We probably best talk about this tomorrow and deploy it before publishing the launch post.

**Comment by fsteeg** [comment]
> Is it possible to assign multiple tags?

Yes, see locally: http://localhost:4000/2017/07/04/lobid-launch.html

> vocabulary-choices.html should definitely be tagged lobid-resources

Pushed the change here.

**Comment by acka47** [comment]
+1

**Pull request merged**
